# Generated by Django 4.2.3 on 2023-07-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_main_footer_image_main_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main_contact',
            new_name='MainContact',
        ),
    ]
