# Generated by Django 4.2.3 on 2023-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_main_contact_maincontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontact',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
