# Generated by Django 4.2.3 on 2023-07-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_maincontact_address_alter_maincontact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontact',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_contact', to='base.main'),
        ),
    ]
