# Generated by Django 4.2.3 on 2023-07-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_product_is_main_service_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Adi'),
            preserve_default=False,
        ),
    ]
